global:
  imageRegistry: "docker.io/bhagyesh1999"
  image:
    tag: "c19b0acc499998dba8719ed72de45308914071db"
  ingress:
    className: "traefik"
    domain: "localhost"

services:
  - name: central
    host: localhost
    image: central
    port: 8080
    path: /central
    replicaCount: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5