{{- range $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      initContainers:
        - name: wait-for-traefik
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "until nslookup traefik.default.svc.cluster.local; do echo waiting for traefik; sleep 2; done;"
      containers:
        - name: {{ $service.name }}
          image: {{ $.Values.global.imageRegistry }}/{{ $service.image }}:{{ $.Values.global.image.tag }}
          ports:
            - containerPort: {{ $service.port }}
      restartPolicy: Always
---
{{- end }}
