{{- range $service := .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $service.name }}-ingress
  annotations:
    acme.cert-manager.io/http01-ingress-class: traefik
    kubernetes.io/ingress.class: "traefik"
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
spec:
  rules:
  # - host: {{ $service.host }}
  - http:
      paths:
        - path: {{ $service.path }}
          pathType: Prefix
          backend:
            service:
              name: {{ $service.name }}-service
              port:
                number: 80
  # tls:
  # - hosts:
  #   - {{ $service.host }}
---
{{- end }}
