{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}-service
spec:
  selector:
    app: {{ $service.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ $service.port }}
---
{{- end }}